language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
  - '3.7-dev'
install:
  - python setup.py install
  - pip install --force-reinstall nbformat
script:
  - python setup.py test
notifications:
  email: false
